version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4-container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - data:/var/lib/pgadmin
